version: '3.1'

services:
  server:
    build: 
      context: ./application
    container_name: login-webserver
    restart: always
    ports:
      - 80:80
    volumes:
      - ./application/source:/var/www/html
    env_file:
      - ./docker.env
    networks:
      - login

  database:
    image: mariadb:latest
    container_name: login-database
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - login_data:/var/lib/mysql
    env_file:
      - ./docker.env
    networks:
      - login

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: login-phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file:
      - ./docker.env
    depends_on:
      - database
    networks:
      - login

networks:
  login:

volumes:
  login_data:
